import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import packageJson from "../../package.json"
const inter = Inter({ subsets: ["latin"] });
/*
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};*/

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <html lang="en">
      <head>
        <title>Tiziano e Martina</title>
      </head>
      <body>
        {children}
        <footer>v{packageJson.version}</footer>
      </body>
    </html>
  );
}
